"use strict";
exports.__esModule = true;
var Person_js_1 = require("./entities/Person.js");
var Document_js_1 = require("./entities/Document.js");
var Periodical_js_1 = require("./entities/Periodical.js");
var Gender_js_1 = require("./entities/Gender.js");
var person1 = new Person_js_1["default"]('João', new Date(1989, 12, 12), Gender_js_1["default"].Male);
var person2 = new Person_js_1["default"]('José', new Date(1985, 3, 14), Gender_js_1["default"].Male);
var person3 = new Person_js_1["default"]('Maria', new Date(1994, 5, 6), Gender_js_1["default"].Female);
var person4 = new Person_js_1["default"]('Marta', new Date(1979, 8, 21), Gender_js_1["default"].Female);
var Document1 = new Document_js_1["default"]('titulo qualquer', 'subtitulo qualquer', new Date(2005, 5, 7), person1);
var Document2 = new Document_js_1["default"]('titulo qualquer', 'subtitulo qualquer', new Date(2001, 6, 8), person2);
var Document3 = new Document_js_1["default"]('titulo qualquer', 'subtitulo qualquer', new Date(20017, 7, 17), person3);
var Document4 = new Document_js_1["default"]('titulo qualquer', 'subtitulo qualquer', new Date(1997, 1, 28), person4);
var periodical1 = new Periodical_js_1["default"](12, 1, 4, Document1.title, Document1.subtitle, Document1.publishedAt, person1);
var periodical2 = new Periodical_js_1["default"](12, 1, 4, Document2.title, Document2.subtitle, Document2.publishedAt, person2);
var periodical3 = new Periodical_js_1["default"](12, 1, 4, Document3.title, Document3.subtitle, Document3.publishedAt, person3);
var periodical4 = new Periodical_js_1["default"](12, 1, 4, Document4.title, Document4.subtitle, Document4.publishedAt, person4);
console.log(person1);
console.log(person2);
console.log(person3);
console.log(person4);
console.log(Document1);
console.log(Document2);
console.log(Document3);
console.log(Document4);
console.log(periodical1);
console.log(periodical2);
console.log(periodical3);
console.log(periodical4);
